paises = {
    0: {
        "nombre": "Holanda",
        "atq": ["Danjuma", "Depay", "De jong"],
        "dfc": ["Van Dijk", "Dunmfries", "De Vrij"],
        "arquero": "Biljow",
        "datos": ["A", 9, 3],
        "ranking": 2,
        "mayorPosicion": "",
    },
    1: {
        "nombre": "Qatar ",
        "atq": ["Afif","Almoez Ali", "Hassan Al-Haidos"],
        "dfc": ["Hassan", "Koukhi", "Hisham"],
        "arquero": "Barshan",
        "datos": ["A", 6, 4],
        "ranking": 3,
        "mayorPosicion": "",
    },
    2: {
        "nombre": "Ecuador",
        "atq": ["Valencia", "Mena", "Plata"],
        "dfc": ["Preciado", "Estrada", "Torres"],
        "arquero": "Alexander Dominguez",
        "datos": ["A", 0, 2],
        "ranking": 2,
        "mayorPosicion": "",
    },
    3: {
        "nombre": "Senegal",
        "atq": ["Mane", "Sarr", "Mendy"],
        "dfc": ["Diallo", "Ciss", "Sarr"],
        "arquero": "Mendy",
        "datos": ["A", 1, 0],
        "ranking": 2,
        "mayorPosicion": "",
    },
    4: {
        "nombre": "Iran  ",
        "atq": ["Taremi", "Azmoun", "Ezatolahi"],
        "dfc": ["Gholizadeh", "Mohammadi", "Kanani"],
        "arquero": "Beiranvand",
        "datos": ["B", 0, 0],
        "ranking": 3,
        "mayorPosicion": "",
    },
    5: {
        "nombre": "Inglaterra",
        "atq": ["Shaw", "Stones", "Foden"],
        "dfc": ["Maguire", "Kane", "Sterling"],
        "arquero": "Pickford",
        "datos": ["B", 0, 0],
        "ranking": 1,
        "mayorPosicion": "",
    },
    6: {
        "nombre": "Gales ",
        "atq": ["Rodon", "Williams", "Davies"],
        "dfc": ["Bale", "Moore", "James"],
        "arquero": "Hennessey",
        "datos": ["B", 0, 0],
        "ranking": 3,
        "mayorPosicion": "",
    },
    7: {
        "nombre": "EEUU  ",
        "atq": ["Pulisic", "A. Robinson", "Pepi"],
        "dfc": ["Dest", "T. Adams", "Musah"],
        "arquero": "Steffen",
        "datos": ["B", 0, 0],
        "ranking": 2,
        "mayorPosicion": "",
    },
    8: {
        "nombre": "Argentina",
        "atq": ["Messi", "De Paul", "Di Maria"], 
        "dfc": ["Paredes", "Romero", "Otamendi"],
        "arquero": "Dibu Martinez",
        "datos": ["C", 0, 0],
        "ranking": 1,
        "mayorPosicion": "",
    },
    9: {
        "nombre": "Mexico",
        "atq": ["Lozano", "Corona", "Herrera"],
        "dfc": ["Sanchez", "Montes", "Vasquez"],
        "arquero": "Ochoa",
        "datos": ["C", 1, 0],
        "ranking": 2,
        "mayorPosicion": "",
    },
    10: {
        "nombre": "Polonia",
        "atq": ["Lewandowski", "Moder", "Zielinksi"],
        "dfc": ["Glik", "Cash", "Bednarek"],
        "arquero": "Szczesny",
        "datos": ["C", 0, 0],
        "ranking": 2,
        "mayorPosicion": "",
    },
    11: {
       "nombre": "Arabia S.",
       "atq": ["Al Faraj", "Al Muwallad", "Al Brikan"],
       "dfc": ["Al-Ghannam", "Al Amri", "Al Bulaihi"],
       "arquero": "Al Owais",
       "datos": ["C", 0, 0],
       "ranking": 3,
       "mayorPosicion": "",
    },
    12: {
        "nombre": "Dinamarca",
        "atq": ["Kjaer", "Poulsen", "Delaney"],
        "dfc": ["Christensen", "Wass", "Skov Olsen"],
        "arquero": "Schmeichel",
        "datos": ["D", 0, 0],
        "ranking": 2,
        "mayorPosicion": "",
    },
    13: {
        "nombre": "Australia",
        "atq": ["Rowles", "Boyle", "Behich"], 
        "dfc": ["Mabil","Hrustic", "Wright"],
        "arquero": "Ryan",
        "datos": ["D", 0, 0],
        "ranking": 3,
        "mayorPosicion": "",
    },
    14: {
        "nombre": "Francia",
        "atq": ["Mpabbe", "Pogba","Griezmann"],
        "dfc": ["Varane", "Benzema", "Kounde"],
        "arquero": "Lloris",
        "datos": ["D", 0, 0],
        "ranking": 1,
        "mayorPosicion": "",
    },
    15: {
        "nombre": "Tunez ",
        "atq": ["Jaziri", "Khazri", "Msakni"],
        "dfc": ["Talbi", "Maaloul", "Ghandri"],
        "arquero": "Ben Said",
        "datos": ["D", 0, 0],
        "ranking": 3,
        "mayorPosicion": "",
    },
    16: {
        "nombre": "Alemania",
        "atq": ["T. Müller", "T. Werner", "Gnabry"],
        "dfc": ["Sule", "Tisch", "Raum"],
        "arquero": "Neuer",
        "datos": ["E", 0, 0],
        "ranking": 1,
        "mayorPosicion": "",
    },
    17: {
        "nombre": "Costa Rica",
        "atq": ["Oviedo", "Calvo", "Tejeda"],
        "dfc": ["Torres" , "Campbell", "Fuller"],
        "arquero": "Keylor Navas",
        "datos": ["E", 0, 0],
        "ranking": 3,
        "mayorPosicion": "",
    },
    18: {
        "nombre": "España",
        "atq": ["Pedri", "Morata", "Dani Olmo"],
        "dfc": ["Jordi Alba", "Laporte", "Eric Garcia"],
        "arquero": "Unai Simon",
        "datos": ["E", 0, 0],
        "ranking": 1,
        "mayorPosicion": "",
    },
    19: {
        "nombre": "Japon ",
        "atq": ["Minamino","Tanaka","J. Ito"],
        "dfc": ["Tomiyasu", "Nagatomo", "Sakai"],
        "arquero": "Gonda",
        "datos": ["E", 0, 0],
        "ranking": 2,
        "mayorPosicion": "",
    },
    20: {
        "nombre": "Belgica",
        "atq": ["Kevin De Bruyne", "Eden Hazard", "De Bruyne"],
        "dfc": ["Denayer", "Vertoghen", "Witsel"],
        "arquero": "Courtois",
        "datos": ["F", 0, 0],
        "ranking": 1,
        "mayorPosicion": "",
    },
    21: {
        "nombre": "Canada",
        "atq": ["Larin", "Laryea", "Buchanan"],
        "dfc": ["Miller", "S. Vitoria", "Johnston"],
        "arquero": "Borjan",
        "datos": ["F", 0, 0],
        "ranking": 2,
        "mayorPosicion": "",
    },
    22: {
        "nombre": "Marruecos",
        "atq": ["Louza","Amallah","El Kaabi"],
        "dfc": ["Aguerd", "Masina", "Saiss"],
        "arquero": "Bounou",
        "datos": ["F", 0, 0],
        "ranking": 3,
        "mayorPosicion": "",
    },
    23: {
        "nombre": "Croacia",
        "atq": ["Kovacic", "Modric", "Juranovic"],
        "dfc": ["Vlasic", "Perisic", "Sosa"],
        "arquero": "Grbic",
        "datos": ["F", 0, 0],
        "ranking": 2,
        "mayorPosicion": "",
    },
    24: {
        "nombre": "Brasil",
        "atq": ["Neymar Jr.", "Vini Jr.", "Paqueta"],
        "dfc": ["Casemiro", "Danilo", "Thiago Silva"],
        "arquero": "Alisson",   
        "datos": ["G", 0, 0],
        "ranking": 1,
        "mayorPosicion": "",
    },
    25: {
        "nombre": "Camerun",
        "atq": ["Fai","Ondoua", "Ngadeu"], 
        "dfc": ["Aboubakar", "Choupo-Moting", "Castelleto"],
        "arquero": "Onana",
        "datos": ["G", 0, 0],
        "ranking": 3,
        "mayorPosicion": "",
    },
    26: {
        "nombre": "Serbia",
        "atq": ["Kostic", "Mitrovic", "Tadic"],
        "dfc": ["Pavlovic", "Veljkovic", "Milenkovic"],
        "arquero": "Rajkovic",
        "datos": ["G", 0, 0],
        "ranking": 3,
        "mayorPosicion": "",
    },
    27: {
        "nombre": "Suiza ",
        "atq": ["Zakaria", "Vargas", "Okafor"],
        "dfc": ["Mbabu", "Akanji", "Rodriguez"],
        "arquero": "Sommer",
        "datos": ["G", 0, 0],
        "ranking": 3,
        "mayorPosicion": "",
    },
    28: {
        "nombre": "Corea del Sur",
        "atq": ["Min-Jae", "Jin-Su", "Hee-Chan"],
        "dfc": ["Jae-Sung", "Young-Gwon", "Lee young"],
        "arquero": "Seung-Gyu",
        "datos": ["H", 0, 0],
        "ranking": 3,
        "mayorPosicion": "",
    },
    29: {
        "nombre": "Ghana ",
        "atq": ["Kudus", "Thomas Partey", "Fatawu"],
        "dfc": ["Amartey","Baba", "Djiuku"],
        "arquero": "Wollacott",
        "datos": ["H", 4, 0],
        "ranking": 3,
        "mayorPosicion": "",
    },
    30: {
        "nombre": "Portugal",
        "atq": ["Ronaldo", "Jota", "Fernades"],
        "dfc": ["Dias", "Pepe", "Cancelo"],
        "arquero": "Costa",
        "datos": ["H", 1, 0],
        "ranking": 1,
        "mayorPosicion": "", 
    },    
    31: {
        "nombre": "Uruguay",
        "atq": ["Suarez", "Nuñez", "Valverde"],
        "dfc": ["Gimenez", "Godin", "Araujo"],
        "arquero": "Rochet",
        "datos": ["H", 10, 0],
        "ranking": 1,
        "mayorPosicion": "",
    },
}


# for pais in paises:
#     print(pais)
#     print(paises[pais])
#     print(paises[pais]["atq"])
#     print(paises[pais]["dfc"][0])
#     print(paises[pais]["datos"][0])
#     print()


# for i in range(len(paises)):
#     print(f'{paises[i]["datos"][1]}')

# for pais, datos in paises.items():
#     print("Jugador de {}: {}".format(pais, datos["jugadores"][0]))